[package]
name = "cookiebot"
version = "0.1.3"
authors = ["Chronophylos <nikolai@chronophylos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.3.9"
ron = "0.6.2"
serde = { version = "1.0.116", features = ["derive"] }
anyhow = "1.0.32"
twitchchat = { version = "0.14.1", features = ["async", "smol", "async-tls"] }
smol = "1.2.2"
log = "0.4.11"
env_logger = "0.7.1"
either = "1.6.1"
