name: CI

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        
      - name: Install stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Cache rust
        uses: Swatinem/rust-cache@v1

      - name: Run tests
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --verbose

      - name: Build binary
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          toolchain: nightly
          args: -Z unstable-options --release --out-dir artifacts --verbose

      - name: Strip binary
        if: startsWith(github.ref, 'refs/tags/')
        run: strip -s artifacts/cookiebot

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
              artifacts/cookiebot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}